spkapp/urls.py
from django.contrib import admin
from django.urls import path, include
from spkapp import views


urlpatterns = [
    path('', views.dologin, name="dologin"),
    path('dohome/', views.dohome, name="dohome"),
    path('dologout/', views.dologout, name="dologout"),
    path('orders/', views.orders, name='orders'),
    #  path('approveorder/', views.approveOrder, name="approveorder"),
    path('editorder/<order_id>', views.editOrder, name="editorder"),
    path('orderdetails/', views.orderDetails, name="orderdetails"),
    path('vieworder/', views.viewOrder, name="vieworder"),
    path('report/', views.viewReport, name="report"),
    path('registration/', views.userRegistration, name="registration"),
    path('ajax/load-cities/', views.load_cities, name='ajax_load_cities'),  # AJAX
    path('exporttoCSV/', views.exporttoCSV, name="exporttoCSV"),
    path('loadproducts/', views.loadproducts, name='ajax_load_cities'),
    path('approveorder/<status>', views.approveOrder_new, name="approveorder"),
    path('report_dup/', views.viewReport_dup, name="report_dup")

]

spkdev/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('spkapp.urls')),
    path("accounts/", include("django.contrib.auth.urls")),  # new
]

spkapp/models.py
from email.policy import default
from django.db import models
from django.utils import timezone


# Create your models here.
class Projects(models.Model):
    name = models.CharField(max_length=40)

    def __str__(self):
        return self.name


class Vendor(models.Model):
    name = models.CharField(max_length=40)
    email = models.EmailField(max_length=40)
    phone = models.CharField(max_length=20)

    def __str__(self):
        return self.name


class Units(models.Model):
    name = models.CharField(max_length=40)

    def __str__(self):
        return self.name


class Category(models.Model):
    name = models.CharField(max_length=40)

    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    # name = models.CharField(max_length=40, default='NA')
    name = models.CharField(max_length=40)

    def __str__(self):
        return self.name


class order_model(models.Model):
    orderno = models.CharField(max_length=10, default='SPK-00001')
    status = (('Requested', 'Requested'), ('Checked', 'Checked'), ('Approved', 'Approved'), ('Rejected', 'Rejected'),)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, blank=True, null=True)
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, blank=True, null=True)
    requester = models.CharField(max_length=40)
    projectname = models.ForeignKey(Projects, on_delete=models.SET_NULL, blank=True, null=True)
    approver = models.CharField(max_length=40)
    status = models.CharField(max_length=10, choices=status, default='Requested')
    quantity = models.IntegerField()
    unit = models.ForeignKey(Units, on_delete=models.SET_NULL, blank=True, null=True)
    remarks = models.TextField(blank=True, null=True)
    vendor = models.ForeignKey(Vendor, on_delete=models.SET_NULL, blank=True, null=True)
    order_date = models.DateField(auto_now_add=True, auto_now=False)
    approved_date = models.DateField(auto_now=True)

    def __str__(self):
        return 'Order details shared'

spkapp/forms.py
from django import forms
from django.forms import ModelForm
from .models import order_model, Category, Product


# create a order form

class order_form(ModelForm):
    class Meta:
        model = order_model
        fields = ('projectname', 'category', 'product', 'quantity', 'unit', 'vendor', 'remarks', 'status')

        def __init__(self, *args, **kwargs):
            super().__init__(*args, **kwargs)
            self.fields['product'].queryset = Product.objects.none()

            if 'category' in self.data:
                try:
                    category_id = int(self.data.get('category'))
                    self.fields['product'].queryset = Product.objects.filter(category_id=category_id).order_by('name')
                except (ValueError, TypeError):
                    pass  # invalid input from the client; ignore and fallback to empty City queryset
            elif self.instance.pk:
                self.fields['product'].queryset = self.instance.category.product_set.order_by('name')

spkapp/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from .forms import order_form
from .models import order_model, Product, Projects, Category, Units, Vendor
from django.http import HttpResponseRedirect, HttpResponse
import csv
import datetime
from django.db.models import Sum

# Create your views here.

def dologin(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('dohome')
            # Redirect to a success page.
        else:
            messages.success(request, "There was an error, Try login again...!")
            return redirect('dologin')
            # Return an 'invalid login' error message
    else:
        return render(request, 'login/dologin.html')


def dohome(request):
    all_orders = order_model.objects.all()
    return render(request, 'home/dohome.html', {'all': all_orders})


def dologout(request):
    logout(request)
    messages.success(request, "You were logged out ...!")
    return redirect('dologin')


def newOrder(request):
    return render(request, 'order/new_order.html', {})


def viewOrder(request):
    all_orders = order_model.objects.all()
    return render(request, 'order/view_order.html', {'all': all_orders})


def editOrder_old(request, order_id):
    order = order_model.objects.get(pk=order_id)
    form = order_form(request.POST or None, instance=order)
    if form.is_valid():
        task_list = form.save(commit=False)
        task_list.approver = request.user.username
        task_list.save()
        return redirect('approveorder')
    return render(request, 'order/edit_order.html', {'order': order, 'form': form})

def editOrder(request, order_id):
    order = order_model.objects.get(pk=order_id)
    form = order_form(request.POST or None, instance=order)
    if request.method == 'POST':
        oprojectname = request.POST.get('projectname')
        projectname = Projects.objects.get(id=oprojectname)
        ocategory = request.POST.get('category')
        category = Category.objects.get(id=ocategory)  
        oproduct = request.POST.get('product')
        product = Product.objects.get(id=oproduct)
        quantity = request.POST.get('quantity')
        ounit = request.POST.get('unit')
        unit = Units.objects.get(id=ounit)
        ovendor = request.POST.get('vendor')
        if ovendor != "":
            vendor = Vendor.objects.get(id=ovendor)
            order.vendor = vendor
        remarks = request.POST.get('remarks')
        status = request.POST['status']
        order.category = category
        order.projectname = projectname
        order.product = product
        order.quantity = quantity
        order.remarks = remarks
        order.status = status
        order.unit = unit
        order.approver = request.user.username
        order.save()
        submitted =True
        return render(request, 'order/postorderform.html', {'submitted': submitted})
    else:
         return render(request, 'order/edit_order.html', {'order': order, 'form': form})

def approveOrder(request):
    all_orders = order_model.objects.all()
    return render(request, 'order/approve_order.html', {'all': all_orders})


#def viewReport(request):
#    return render(request, 'report/viewreport.html', {})


def orderDetails(request):
    return render(request, 'order/order_detail.html', {})


def userRegistration(request):
    return render(request, 'registration/user_registration.html', {})


def formorder(request):
    submitted = False
    if request.method == "POST":
        form = order_form(request.POST)
        if form.is_valid():
            form.cleaned_data['order_date']
            task_list = form.save(commit=False)
            task_list.requester = request.user
            task_list.save()
            return HttpResponseRedirect('/formorder?submitted=True')
    else:
        form = order_form
        if 'submitted' in request.GET:
            submitted = True
    return render(request, 'order/postorderform.html', {'form': form, 'submitted': submitted})


def load_cities1(request):
    category_id = request.GET.get('category_id')
    products = Product.objects.filter(category_id=category_id).all()
    return render(request, 'persons/city_dropdown_list_options.html', {'cities': products})
    # return JsonResponse(list(cities.values('id', 'name')), safe=False)


def load_cities(request):
    category = request.GET.get('category')
    products = Product.objects.filter(category=category).all()
    return render(request, 'order/orders.html', {'products': products})
    # return JsonResponse(list(cities.values('id', 'name')), safe=False)


def loadproducts(request):
    category_id = request.GET.get('category')
    products = Product.objects.filter(category_id=category_id).order_by('name')
    return render(request, 'order/courses_dropdown_list_options.html', {'products': products})


def formorder1(request):
    submitted = False
    if request.method == "POST":
        form = order_form(request.POST)
        if form.is_valid():
            form.cleaned_data['order_date']
            task_list = form.save(commit=False)
            task_list.requester = request.user
            task_list.save()
            return HttpResponseRedirect('/formorder?submitted=True')
    else:
        form = order_form
        if 'submitted' in request.GET:
            submitted = True
    return render(request, 'order/test2.html', {'form': form, 'submitted': submitted})


def exporttoCSV(request):
    response = HttpResponse()
    response['content_type'] = 'text/csv'
    response['Content-Disposition'] = 'attachment;filename=order.csv'
    # create a CSV writer
    writer = csv.writer(response)
    orders = order_model.objects.all()
    # add column heading to CSV file

    writer.writerow(
        ['#', 'Order No','Order Date', 'Requester', 'Project Name', 'Product Category', 'Product', 'Quantity', 'Unit', 'Remarks',
         'Approver', 'Approved Date', 'Status'])

    # loop through the order
    i = 0
    for order in orders:
        i = i + 1
        writer.writerow(
            [i, order.orderno, order.order_date, order.requester, order.projectname, order.category, order.product, order.quantity,
             order.unit, order.remarks, order.approver, order.approved_date, order.status])

    return response

def orders(request):
    submitted = False
    if request.method == "POST":
        oprojectname = request.POST.get('projectname')
        projectname = Projects.objects.get(id=oprojectname)
        ocategory = request.POST.getlist('programming[]')
        oproduct = request.POST.getlist('product[]')
        oquantity = request.POST.getlist('quantity[]')
        ounit = request.POST.getlist('unit[]')
        oremarks = request.POST.getlist('remarks[]')
        order_date = datetime.datetime.now()
        status = "Requested"
        count = len(ocategory)
        orderno = order_model.objects.latest('id')
        orderno = orderno.pk
        for i in range(count):
            orderno = int(orderno) + 1
            category = Category.objects.get(id=ocategory[i])
            product = Product.objects.get(id=oproduct[i])
            quantity = oquantity[i]
            unit = Units.objects.get(id=ounit[i])
            remarks = oremarks[i]
            order = order_model()
            order.category = category
            order.order_date = order_date
            order.projectname = projectname
            order.product = product
            order.quantity = quantity
            order.remarks = remarks
            order.status = status
            order.unit = unit
            order.orderno = 'SPK-' + str(orderno).zfill(6) 
            order.requester = request.user
            order.save()
       # return HttpResponseRedirect('/orders?submitted=True')
        return render(request, 'order/postorderform.html', {'submitted': 'True'})
    else:
        projects = Projects.objects.all()
        categories = Category.objects.all()
        punits = Units.objects.all()
        return render(request, 'order/orders.html', {'cities': projects, 'categories': categories, 'punits': punits})


def viewReport(request):
    if request.method == "POST":
        odate = request.POST.get('order_date')
        #if odate == "":
       #     return render(request, 'report/report_dup.html', {'cities': projects, 'categories': categories, 'punits': punits,'mylist': mylist})
       # else:
        orders_new = order_model.objects.filter(order_date = odate).order_by("id")
        #  orders_new = order_model.objects.values('category','product').order_by().annotate(Sum('quantity'))
        # orders = order_model.objects.filter(projectname_id=oprojectname).order_by("id")
        # return HttpResponseRedirect('/orders?submitted=True')
        projects = Projects.objects.all()
        categories = Category.objects.all()
        stat= order_model._meta.get_field('status').choices
        mylist = [(stat[0][0]), (stat[1][0]), (stat[2][0])]
        return render(request, 'report/report.html', {'cities': projects, 'categories': categories,'orders': orders_new,'mylist': mylist})
    else:
        projects = Projects.objects.all()
        categories = Category.objects.all()
        punits = Units.objects.all()
        #stat= order_model.status
        stat= order_model._meta.get_field('status').choices
        mylist = [(stat[0][0]), (stat[1][0]), (stat[2][0]),(stat[3][0])]
        return render(request, 'report/report.html', {'cities': projects, 'categories': categories, 'punits': punits,'mylist': mylist})

def approveOrder_new(request, status):
    all_orders = order_model.objects.filter(status=status)
   # Model.objects.values('product', 'condition').order_by().annotate(Sum('quantity'))

spkapp/templates/report/report.html
{% extends 'home/navi.html' %}
{% load static %}
{% block content %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Order Details</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
</head>

<style>

.my-custom-scrollbar {
    position: relative;
    height: 620px;
    overflow: auto;
    width: 100%;
    table-layout: auto;
}
</style>

<br><br>
<br>
{% if user.is_authenticated %}
<h3 class="text-center">Report</h3>
<div class="container-fluid well">
    {% if submitted %}
      Your order was submitted successfully!!
    {% else %}
    <form action=""  id="personForm" class="order" data-cities-url="{% url 'ajax_load_cities' %}" method="POST">
        {% csrf_token %}

                <div class="form-group col-md-2 mb-2">
                        <p>Project Name</p>
                        <select class="form-control" name ="projectname" >
                        <option disabled="true" selected>----Select Project Name----</option>
                        {{cities}}
                            {% for project in cities %}
                            <option value="{{project.id}}">{{project.name}}</option>
                            {% endfor %}
                        </select>
                </div>
                <div class="form-group col-md-2 margin-left--10">
                        <p>Category</p>
                           <select name="programming" id="programming" class="form-control" onchange="populate(this.id)">
                           <option disabled="true" selected>--Select Category--</option>
                           {{categories}}
                            {% for cat in categories %}
                            <option value="{{cat.id}}">{{cat.name}}</option>
                            {% endfor %}
                        </select>
                </div>
                <div class="form-group col-md-2 margin-right--10">
                        <p>Product</p>
                        <select class="form-control" name ="product" id="id_product">
                        </select>
                </div>
                <div class="form-group col-md-2 margin-right--10">
                    <p>Status</p>
                    <select class="form-control" name ="product" id="id_product">
                    </select>
                 </div>
                <div class="form-group col-md-2 center-align">
                        <p>.</p>
                        <button class="btn btn-success add_item_btn" style = "padding-left: 10px;" onclick="populate()">Generate</button>
                 </div>
                <div class="form-group col-md-2 margin-left--3">
                    <p>.</p>
                    <a href="{% url 'exporttoCSV' %}"  class="btn btn-success" role="button">Export To Excel</a>
                 </div>

    </form>
</div>
{% if orders %}
<div class="container-fluid text-center table-wrapper-scroll-y my-custom-scrollbar">
    <table class="table table-bordered" style="border: 1px solid;">
        <thead>
            <tr>
                    <th scope="col">#</th>
                    <th scope="col">Order Date</th>
                    <th scope="col">Requester</th>
                    <th scope="col">Project Name</th>
                    <th scope="col">Product Category</th>
                    <th scope="col">Product</th>
                    <th scope="col">Quantity</th>
                    <th scope="col">Unit</th>
                    <th scope="col">Remarks</th>
                    <th scope="col">Approver</th>
                    <th scope="col">Date</th>
                    <th scope="col">Status</th>
            </tr>
          </thead>

        <tbody>
            {% for order in orders %}
          <tr class="table-info">
              <th scope="row">{{ forloop.counter }}</th>
              <td>{{order.order_date}} </td>
              <td>{{order.requester}} </td>
              <td>{{order.projectname}} </td>
              <td>{{order.category}} </td>
              <td>{{order.product}} </td>
              <td>{{order.quantity}} </td>
              <td>{{order.unit}} </td>
              <td>{{order.remarks}} </td>
              <td>{{order.approver}} </td>
              <td>{{order.approved_date}} </td>
              <td>{{order.status}} </td>
          </tr>
          {% endfor %}
        <tbody>

    </table>
</div>
{% endif %}
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script>

    function populate(c1){
        var y = c1.split("_")
        var c1=document.getElementById(c1);
        var url = $("#personForm").attr("data-cities-url");  // get the url of the `load_courses` view
        var programmingId = c1.value; // get the selected programming ID from the HTML input
        $.ajax({                       // initialize an AJAX request
            url: url,                    // set the url of the request (= localhost:8000/load-courses/)
            data: {
            'category': programmingId       // add the programming id to the GET parameters
            },
            success: function (data) {   // `data` is the return of the `load_courses` view function
            $("#id_product").html(data);  // replace the contents of the course input with the data that came from the server
            }
        });
    }


</script>
    {% endif %}
{% else %}
Login First
{% endif %}

{% endblock %}

spkapp/templates/report/report_dup.html
{% extends 'home/navi.html' %}
{% load static %}
{% block content %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Order Details</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
</head>

<style>

.my-custom-scrollbar {
    position: relative;
    height: 620px;
    overflow: auto;
    width: 100%;
    table-layout: auto;
}
</style>

<br><br>
<br>
{% if user.is_authenticated %}
<h3 class="text-center">Report</h3>
<div class="container-fluid well">
    {% if submitted %}
      Your order was submitted successfully!!
    {% else %}
    <form action=""  id="personForm" class="order" data-cities-url="{% url 'ajax_load_cities' %}" method="POST">
        {% csrf_token %}
        {{orders|safe}}
                <div class="form-group col-md-2 mb-2">
                        <p><b>Project Name</b></p>
                        <select class="form-control" name ="projectname" >
                        <option disabled="true" selected>----Select Project Name----</option>
                            {% for project in cities %}
                            <option value="{{project.id}}">{{project.name}}</option>
                            {% endfor %}
                        </select>
                </div>
                <div class="form-group col-md-2 margin-left--2">
                        <p><b>Category</b></p>
                           <select name="programming" id="programming" class="form-control" onchange="populate(this.id)">
                           <option disabled="true" selected>--Select Category--</option>
                            {% for cat in categories %}
                            <option value="{{cat.id}}">{{cat.name}}</option>
                            {% endfor %}
                        </select>
                </div>
                <div class="form-group col-md-2 margin-right--2">
                        <p><b>Product</b></p>
                        <select class="form-control" name ="product" id="id_product">
                        </select>
                </div>
                <div class="form-group col-md-2 margin-right--2">
                    <p><b>Status</b></p>
                    <select class="form-control" name ="status" id="id_status">
                    <option disabled="true" selected>----Select Status----</option>

                        {% for status in mylist %}
                        <option>{{status}}</option>
                        {% endfor %}

                    </select>
                 </div>
                 <div class="form-group col-md-2 margin-right--2">
                    <p><b>Order Date</b></p>
                    <input class="form-control" type="date" id="order_date" name="order_date">
                 </div>
                <div class="form-group col-md-1 center-align">
                        <p>.</p>
                        <button class="btn btn-success add_item_btn" style = "padding-left: 10px;" >Generate</button>
                 </div>
                <div class="form-group col-md-1 margin-left--2">
                    <p>.</p>
                    <a href="{% url 'exporttoCSV' %}"  class="btn btn-success" role="button">Export To Excel</a>
                 </div>

    </form>
</div>
{% if orders %}
<div class="container-fluid text-center table-wrapper-scroll-y my-custom-scrollbar">   
    <table class="table table-bordered" style="border: 1px solid; ">
        <thead>
            <tr>
                    <th scope="col">#</th>
                    <th scope="col">Project Name</th>
                    <th scope="col">Product Category</th>
                    <th scope="col">Product</th>
                    <th scope="col">Quantity</th>
            </tr>
          </thead>
        
        <tbody>
            {% for order in orders %}
          <tr class="table-info">
              <th scope="row">{{ forloop.counter }}</th>
              <td>{{order.projectname}} </td>
              <td>{{order.category}} </td>
              <td>{{order.product}} </td>
              <td>{{order.quantity__sum}} </td>
          </tr>
          {% endfor %}
        <tbody>
       
    </table>
</div>
{% endif %}
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script>
	
    function populate(c1){
        var y = c1.split("_")
        var c1=document.getElementById(c1);
        var url = $("#personForm").attr("data-cities-url");  // get the url of the `load_courses` view
        var programmingId = c1.value; // get the selected programming ID from the HTML input
        $.ajax({                       // initialize an AJAX request
            url: url,                    // set the url of the request (= localhost:8000/load-courses/)
            data: {
            'category': programmingId       // add the programming id to the GET parameters
            },
            success: function (data) {   // `data` is the return of the `load_courses` view function
            $("#id_product").html(data);  // replace the contents of the course input with the data that came from the server
            }
        });
    }
    

</script>
    {% endif %}
{% else %}
Login First
{% endif %}

{% endblock %}