spkapp/urls.py
from django.contrib import admin
from django.urls import path, include
from spkapp import views


urlpatterns = [
    path('', views.dologin, name="dologin"),
    path('dohome/', views.dohome, name="dohome"),
    path('dologout/', views.dologout, name="dologout"),
    path('orders/', views.orders, name='orders'),
    #  path('approveorder/', views.approveOrder, name="approveorder"),
    path('editorder/<order_id>', views.editOrder, name="editorder"),
    path('orderdetails/', views.orderDetails, name="orderdetails"),
    path('vieworder/', views.viewOrder, name="vieworder"),
    path('report/', views.viewReport, name="report"),
    path('registration/', views.userRegistration, name="registration"),
    path('ajax/load-cities/', views.load_cities, name='ajax_load_cities'),  # AJAX
    path('exporttoCSV/', views.exporttoCSV, name="exporttoCSV"),
    path('loadproducts/', views.loadproducts, name='ajax_load_cities'),
    path('approveorder/<status>', views.approveOrder_new, name="approveorder"),
    path('report_dup/', views.viewReport_dup, name="report_dup")

]

spkdev/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('spkapp.urls')),
    path("accounts/", include("django.contrib.auth.urls")),  # new
]

spkapp/models.py
from email.policy import default
from django.db import models
from django.utils import timezone


# Create your models here.
class Projects(models.Model):
    name = models.CharField(max_length=40)

    def __str__(self):
        return self.name


class Vendor(models.Model):
    name = models.CharField(max_length=40)
    email = models.EmailField(max_length=40)
    phone = models.CharField(max_length=20)

    def __str__(self):
        return self.name


class Units(models.Model):
    name = models.CharField(max_length=40)

    def __str__(self):
        return self.name


class Category(models.Model):
    name = models.CharField(max_length=40)

    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    # name = models.CharField(max_length=40, default='NA')
    name = models.CharField(max_length=40)

    def __str__(self):
        return self.name


class order_model(models.Model):
    orderno = models.CharField(max_length=10, default='SPK-00001')
    status = (('Requested', 'Requested'), ('Checked', 'Checked'), ('Approved', 'Approved'), ('Rejected', 'Rejected'),)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, blank=True, null=True)
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, blank=True, null=True)
    requester = models.CharField(max_length=40)
    projectname = models.ForeignKey(Projects, on_delete=models.SET_NULL, blank=True, null=True)
    approver = models.CharField(max_length=40)
    status = models.CharField(max_length=10, choices=status, default='Requested')
    quantity = models.IntegerField()
    unit = models.ForeignKey(Units, on_delete=models.SET_NULL, blank=True, null=True)
    remarks = models.TextField(blank=True, null=True)
    vendor = models.ForeignKey(Vendor, on_delete=models.SET_NULL, blank=True, null=True)
    order_date = models.DateField(auto_now_add=True, auto_now=False)
    approved_date = models.DateField(auto_now=True)

    def __str__(self):
        return 'Order details shared'

spkapp/forms.py
from django import forms
from django.forms import ModelForm
from .models import order_model, Category, Product


# create a order form

class order_form(ModelForm):
    class Meta:
        model = order_model
        fields = ('projectname', 'category', 'product', 'quantity', 'unit', 'vendor', 'remarks', 'status')

        def __init__(self, *args, **kwargs):
            super().__init__(*args, **kwargs)
            self.fields['product'].queryset = Product.objects.none()

            if 'category' in self.data:
                try:
                    category_id = int(self.data.get('category'))
                    self.fields['product'].queryset = Product.objects.filter(category_id=category_id).order_by('name')
                except (ValueError, TypeError):
                    pass  # invalid input from the client; ignore and fallback to empty City queryset
            elif self.instance.pk:
                self.fields['product'].queryset = self.instance.category.product_set.order_by('name')

spkapp/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from .forms import order_form
from .models import order_model, Product, Projects, Category, Units, Vendor
from django.http import HttpResponseRedirect, HttpResponse
import csv
import datetime
from django.db.models import Sum

# Create your views here.

def dologin(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('dohome')
            # Redirect to a success page.
        else:
            messages.success(request, "There was an error, Try login again...!")
            return redirect('dologin')
            # Return an 'invalid login' error message
    else:
        return render(request, 'login/dologin.html')


def dohome(request):
    all_orders = order_model.objects.all()
    return render(request, 'home/dohome.html', {'all': all_orders})


def dologout(request):
    logout(request)
    messages.success(request, "You were logged out ...!")
    return redirect('dologin')


def newOrder(request):
    return render(request, 'order/new_order.html', {})


def viewOrder(request):
    all_orders = order_model.objects.all()
    return render(request, 'order/view_order.html', {'all': all_orders})


def editOrder_old(request, order_id):
    order = order_model.objects.get(pk=order_id)
    form = order_form(request.POST or None, instance=order)
    if form.is_valid():
        task_list = form.save(commit=False)
        task_list.approver = request.user.username
        task_list.save()
        return redirect('approveorder')
    return render(request, 'order/edit_order.html', {'order': order, 'form': form})

def editOrder(request, order_id):
    order = order_model.objects.get(pk=order_id)
    form = order_form(request.POST or None, instance=order)
    if request.method == 'POST':
        oprojectname = request.POST.get('projectname')
        projectname = Projects.objects.get(id=oprojectname)
        ocategory = request.POST.get('category')
        category = Category.objects.get(id=ocategory)  
        oproduct = request.POST.get('product')
        product = Product.objects.get(id=oproduct)
        quantity = request.POST.get('quantity')
        ounit = request.POST.get('unit')
        unit = Units.objects.get(id=ounit)
        ovendor = request.POST.get('vendor')
        if ovendor != "":
            vendor = Vendor.objects.get(id=ovendor)
            order.vendor = vendor
        remarks = request.POST.get('remarks')
        status = request.POST['status']
        order.category = category
        order.projectname = projectname
        order.product = product
        order.quantity = quantity
        order.remarks = remarks
        order.status = status
        order.unit = unit
        order.approver = request.user.username
        order.save()
        submitted =True
        return render(request, 'order/postorderform.html', {'submitted': submitted})
    else:
         return render(request, 'order/edit_order.html', {'order': order, 'form': form})

def approveOrder(request):
    all_orders = order_model.objects.all()
    return render(request, 'order/approve_order.html', {'all': all_orders})


#def viewReport(request):
#    return render(request, 'report/viewreport.html', {})


def orderDetails(request):
    return render(request, 'order/order_detail.html', {})


def userRegistration(request):
    return render(request, 'registration/user_registration.html', {})


def formorder(request):
    submitted = False
    if request.method == "POST":
        form = order_form(request.POST)
        if form.is_valid():
            form.cleaned_data['order_date']
            task_list = form.save(commit=False)
            task_list.requester = request.user
            task_list.save()
            return HttpResponseRedirect('/formorder?submitted=True')
    else:
        form = order_form
        if 'submitted' in request.GET:
            submitted = True
    return render(request, 'order/postorderform.html', {'form': form, 'submitted': submitted})


def load_cities1(request):
    category_id = request.GET.get('category_id')
    products = Product.objects.filter(category_id=category_id).all()
    return render(request, 'persons/city_dropdown_list_options.html', {'cities': products})
    # return JsonResponse(list(cities.values('id', 'name')), safe=False)


def load_cities(request):
    category = request.GET.get('category')
    products = Product.objects.filter(category=category).all()
    return render(request, 'order/orders.html', {'products': products})
    # return JsonResponse(list(cities.values('id', 'name')), safe=False)


def loadproducts(request):
    category_id = request.GET.get('category')
    products = Product.objects.filter(category_id=category_id).order_by('name')
    return render(request, 'order/courses_dropdown_list_options.html', {'products': products})


def formorder1(request):
    submitted = False
    if request.method == "POST":
        form = order_form(request.POST)
        if form.is_valid():
            form.cleaned_data['order_date']
            task_list = form.save(commit=False)
            task_list.requester = request.user
            task_list.save()
            return HttpResponseRedirect('/formorder?submitted=True')
    else:
        form = order_form
        if 'submitted' in request.GET:
            submitted = True
    return render(request, 'order/test2.html', {'form': form, 'submitted': submitted})


def exporttoCSV(request):
    response = HttpResponse()
    response['content_type'] = 'text/csv'
    response['Content-Disposition'] = 'attachment;filename=order.csv'
    # create a CSV writer
    writer = csv.writer(response)
    orders = order_model.objects.all()
    # add column heading to CSV file

    writer.writerow(
        ['#', 'Order No','Order Date', 'Requester', 'Project Name', 'Product Category', 'Product', 'Quantity', 'Unit', 'Remarks',
         'Approver', 'Approved Date', 'Status'])

    # loop through the order
    i = 0
    for order in orders:
        i = i + 1
        writer.writerow(
            [i, order.orderno, order.order_date, order.requester, order.projectname, order.category, order.product, order.quantity,
             order.unit, order.remarks, order.approver, order.approved_date, order.status])

    return response

def orders(request):
    submitted = False
    if request.method == "POST":
        oprojectname = request.POST.get('projectname')
        projectname = Projects.objects.get(id=oprojectname)
        ocategory = request.POST.getlist('programming[]')
        oproduct = request.POST.getlist('product[]')
        oquantity = request.POST.getlist('quantity[]')
        ounit = request.POST.getlist('unit[]')
        oremarks = request.POST.getlist('remarks[]')
        order_date = datetime.datetime.now()
        status = "Requested"
        count = len(ocategory)
        orderno = order_model.objects.latest('id')
        orderno = orderno.pk
        for i in range(count):
            orderno = int(orderno) + 1
            category = Category.objects.get(id=ocategory[i])
            product = Product.objects.get(id=oproduct[i])
            quantity = oquantity[i]
            unit = Units.objects.get(id=ounit[i])
            remarks = oremarks[i]
            order = order_model()
            order.category = category
            order.order_date = order_date
            order.projectname = projectname
            order.product = product
            order.quantity = quantity
            order.remarks = remarks
            order.status = status
            order.unit = unit
            order.orderno = 'SPK-' + str(orderno).zfill(6) 
            order.requester = request.user
            order.save()
       # return HttpResponseRedirect('/orders?submitted=True')
        return render(request, 'order/postorderform.html', {'submitted': 'True'})
    else:
        projects = Projects.objects.all()
        categories = Category.objects.all()
        punits = Units.objects.all()
        return render(request, 'order/orders.html', {'cities': projects, 'categories': categories, 'punits': punits})


def viewReport(request):
    if request.method == "POST":
        odate = request.POST.get('order_date')
        #if odate == "":
       #     return render(request, 'report/report_dup.html', {'cities': projects, 'categories': categories, 'punits': punits,'mylist': mylist})
       # else:
        orders_new = order_model.objects.filter(order_date = odate).order_by("id")
        #  orders_new = order_model.objects.values('category','product').order_by().annotate(Sum('quantity'))
        # orders = order_model.objects.filter(projectname_id=oprojectname).order_by("id")
        # return HttpResponseRedirect('/orders?submitted=True')
        projects = Projects.objects.all()
        categories = Category.objects.all()
        stat= order_model._meta.get_field('status').choices
        mylist = [(stat[0][0]), (stat[1][0]), (stat[2][0])]
        return render(request, 'report/report.html', {'cities': projects, 'categories': categories,'orders': orders_new,'mylist': mylist})
    else:
        projects = Projects.objects.all()
        categories = Category.objects.all()
        punits = Units.objects.all()
        #stat= order_model.status
        stat= order_model._meta.get_field('status').choices
        mylist = [(stat[0][0]), (stat[1][0]), (stat[2][0]),(stat[3][0])]
        return render(request, 'report/report.html', {'cities': projects, 'categories': categories, 'punits': punits,'mylist': mylist})

def approveOrder_new(request, status):
    all_orders = order_model.objects.filter(status=status)
   # Model.objects.values('product', 'condition').order_by().annotate(Sum('quantity'))

spkapp/templates/order/approve_order.html
{% extends 'home/navi.html' %}
{% load static %}
{% block content %}
<html lang="en">
<head>
    <meta charset="UTF-8">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'approve_order_form.css' %}">
</head>
<body>
   <br><br><br>
   <div class="container-fluid well">
      <div class="form-group col-md-3 margin-left--3 col text-center">
         <a href="{% url 'approveorder' 'Requested' %}"  class="btn btn-warning" role="button">Requested</a>
      </div>
      <div class="form-group col-md-3 margin-left--3 col text-center">
         <a href="{% url 'approveorder' 'Checked' %}"  class="btn btn-info" role="button">Checked</a>
      </div>
      <div class="form-group col-md-3 margin-left--3 col text-center">
         <a href="{% url 'approveorder' 'Approved' %}"  class="btn btn-success" role="button">Approved</a>
      </div>
      <div class="form-group col-md-3 margin-left--3 col text-center">
         <a href="{% url 'approveorder' 'Rejected' %}"  class="btn btn-danger" role="button">Rejected</a>
      </div>
   </div>
<div class="table-wrapper-scroll-y my-custom-scrollbar">
 {% if user.is_authenticated %}

              {% if all %}
             <table class="table-wrapper-scroll-y text-center">
                <thead>
                   <tr>
                      <th scope="col">#</th>
                      <th scope="col">Edit</th>
                      <th scope="col">Order No</th>
                      <th scope="col">Requester</th>
                      <th scope="col">Project Name</th>
                      <th scope="col">Product Category</th>
                      <th scope="col">Product</th>
                      <th scope="col">Quantity</th>
                      <th scope="col">Unit</th>
                      <th scope="col">Remarks</th>
                      <th scope="col">Approver</th>
                      <th scope="col">Vendor</th>
                      <th scope="col">Status</th>
                      <th scope="col">Order Date</th>
                      <th scope="col">Approved Date</th>
                   </tr>
                </thead>
                {% for order in all %}
                <tbody>
                   <tr>
                     <th scope="row">{{ forloop.counter }}</th>
                     <td><a href="{% url 'editorder' order.id %}"> Edit</a> </td>
                     <td>{{order.orderno}} </td>
                     <td>{{order.requester}} </td>
                     <td>{{order.projectname}} </td>
                     <td>{{order.category}} </td>
                     <td>{{order.product}} </td>
                     <td>{{order.quantity}} </td>
                     <td>{{order.unit}} </td>
                     <td>{{order.remarks}} </td>
                     <td>{{order.approver}} </td>
                     <td>{{order.vendor}} </td>
                     <td>{{order.status}} </td>
                     <td>{{order.order_date}} </td>
                     <td>{{order.approved_date}} </td>
                 </tr>
                  </tr>
                </tbody>
                {% endfor %}
             </table>
             {% endif %}
 {% else %}
      Login First
 {% endif %}
</div>
</body>
</html>

{% endblock %}

spkapp/templates/order/courses_dropdown_list_options.html
<option value="">---Select Product---</option>
{% for product in products %}
<option value="{{ product.pk }}">{{ product.name }}</option>
{% endfor %}

spkapp/templates/order/edit_order.html
{% extends 'home/navi.html' %}
{% load static %}
{% block content %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Order Details</title>
     <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
     <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
     <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>

    <link rel="stylesheet" href="{% static 'mul.css' %}">

</head>

<br><br>
<br>
{% if user.is_authenticated %}
<h3 class="text-center">Edit Order</h3>
<div class="container well ">
    {% if submitted %}
      Your order was updated successfully!!
    {% else %}
    <form action=""  id="personForm" class="order" method="POST">
        {% csrf_token %}
        <div class="form-group">
            <div class="row" id="id_repeat">
                <div class="repeat" >
                    <div class="form-group col-md-3 mb-3">
                        <p><b>Project Name</b></p>
                        <select class="form-control" name ="projectname" >
                             {% for project in form.projectname %}
                             {{project}}
                             {% endfor %}
                         </select>
                    </div>
                    <div class="form-group col-md-2 mb-1">
                        <p><b>Category</b></p>
                           <select name="category" id="category" class="form-control">
                                {% for cat in form.category %}
                                {{cat}}
                                {% endfor %}
                           </select>
                    </div>
                    <div class="form-group col-md-2 margin-right-10">
                        <p><b>Product</b></p>
                        <select class="form-control" name ="product" id="id_product">
                            {% for product in form.product %}
                            {{product}}
                            {% endfor %}
                        </select>
                    </div>

                    <div class="form-group col-md-2 margin-right-10">
                        <p><b>Quantity</b></p>
                        <input type="number" value={{order.quantity}} name="quantity" id="q-name" class="form-control">

                    </div>
                    <div class="form-group col-md-2 mb-1">
                        <p><b>Unit</b></p>
                        <select name="unit" class="form-control" id="unit">
                            <option disabled="true" selected>--Select Unit--</option>
                            {% for unit in form.unit %}
                            {{unit}}
                            {% endfor %}
                        </select>
                    </div>

                    <div class="form-group col-md-2 mb-2">
                        <p><b>Remarks</b></p>
                        <input type="text" value = {{order.remarks}} name="remarks" id="remarks" class="form-control">
                    </div>

                    <div class="form-group col-md-2 mb-2">
                        <p><b>Order No</b></p>
                        <input type="text" value = {{order.orderno}} name="orderno" id="orderno" class="form-control" readonly>
                    </div>

                    <div class="form-group col-md-2 mb-2">
                        <p><b>Vendor</b></p>
                        <select class="form-control" name ="vendor" id="id_vendor">
                            {% for ven in form.vendor %}
                            {{ven.name}}
                            {{ven}}
                            {% endfor %}
                        </select>
                        </div>

                    <div class="form-group col-md-2 mb-1">
                        <p><b>Status</b></p>
                        <select name="status" class="form-control">
                            {% for status in form.status %}
                            {{status}}
                            {% endfor %}
                        </select>
                    </div>

                </div>

            </div>
        </div>
                <div class="form-group">
                    <input type="submit" name=""  value="Update Order" class="btn btn-success">
                </div>
    </form>
</div>
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script>


</script>
    {% endif %}
{% else %}
Login First
</div>
{% endif %}

{% endblock %}

spkapp/templates/order/order_detail.html
{% extends 'home/navi.html' %}
{% load static %}
{% block content %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Order Details</title>
</head>
<body>
  Order Details
</body>
</html>

{% endblock %}

spkapp/templates/order/orders.html
{% extends 'home/navi.html' %}
{% load static %}
{% block content %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Order Details</title>
     <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
     <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
     <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>

<br><br>
<br>
{% if user.is_authenticated %}
<h3 class="text-center">New Order</h3>
<div class="container well ">
    {% if submitted %}
      Your order was submitted successfully!!
    {% else %}
    <form action=""  id="personForm" class="order" data-cities-url="{% url 'ajax_load_cities' %}" method="POST">
        {% csrf_token %}
        <div class="form-group">

            <div class="row">

                <div class="form-group col-md-3 mb-3">
                    <p><b>Project Name</b></p>
                    <select class="form-control" name ="projectname" >
                       <option disabled="true" selected>----Select Project Name----</option>
                       {{cities}}
                        {% for project in cities %}
                        <option value="{{project.id}}">{{project.name}}</option>
                        {% endfor %}
                    </select>
                </div>

            </div>

            <div class="row" id="id_repeat">
                <div class="repeat" >
                    <div class="form-group col-md-2 mb-1">
                        <p><b>Category</b></p>

                           <select name="programming[]" id="programming_0" class="form-control" onchange="populate(this.id)">
                           <option disabled="true" selected>--Select Category--</option>
                           {{categories}}
                            {% for cat in categories %}
                            <option value="{{cat.id}}">{{cat.name}}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <div class="form-group col-md-2 margin-right-10">
                        <p><b>Product</b></p>
                        <select class="form-control" name ="product[]" id="id_product_0">
                        </select>
                    </div>

                    <div class="form-group col-md-2 mb-1">
                        <p><b>Quantity</b></p>
                        <input type="number" name="quantity[]" id="q-name" class="form-control">
                    </div>
                    <div class="form-group col-md-2 mb-1">
                        <p><b>Unit</b></p>
                        <select name="unit[]" class="form-control">
                           <option disabled="true" selected>--Select Unit--</option>
                           {{punits}}
                            {% for unit in punits %}
                            <option value="{{unit.id}}">{{unit.name}}</option>
                            {% endfor %}
                        </select>
                    </div>

                    <div class="form-group col-md-2 mb-2">
                        <p><b>Remarks</b></p>
                        <input type="text" name="remarks[]" id="remarks" class="form-control">
                    </div>
                    <div class="form-group col-md-2 mb-2">
                        <p>.</p>
                        <button data-increment="1" class="btn btn-success add_item_btn">Add More</button>
                    </div>
                </div>

            </div>
        </div>
                <div class="form-group">
                    <input type="submit" name=""  value="Submit Order" class="btn btn-success">
                </div>
    </form>
</div>
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script>
    let x = 0;
    $(document).ready(function(){
        $(".add_item_btn").click(function(e){
            $newid = $(this).data("increment");
            x = x + 1;
            e.preventDefault();
            $("#id_repeat").prepend(`
                <div class="repeat" >
                    <div class="form-group col-md-2 mb-1">
                        <p>Category</p>
                           <select name="programming[]" value="programming1[]" id="programming`+`_`+ x +`" class="form-control" onchange="populate(this.id)">
                           <option disabled="true" selected>--Select Category--</option>
                           {{categories}}
                            {% for cat in categories %}
                            <option value="{{cat.id}}">{{cat.name}}</option>
                            {% endfor %}
                        </select>
                    </div>

                    <div class="form-group col-md-2 margin-right-10">
                        <p>Product</p>
                        <select class="form-control" name ="product[]" id="id_product`+`_`+ x +`">
                        </select>
                    </div>
                    <div class="form-group col-md-2 mb-1">
                        <p>Quantity</p>
                        <input type="number" name="quantity[]" id="q-name" class="form-control">
                    </div>
                    <div class="form-group col-md-2 mb-1">
                        <p>Unit</p>
                        <select name="unit[]" class="form-control">
                           <option disabled="true" selected>--Select Unit--</option>
                           {{punits}}
                            {% for unit in punits %}
                            <option value="{{unit.id}}">{{unit.name}}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <div class="form-group col-md-2 mb-2">
                        <p>Remarks</p>
                        <input type="text" name="remarks[]" id="remarks" class="form-control">
                    </div>
                    <div class="form-group col-md-2 mb-2">
                        <p>.</p>
                        <button class="btn btn-danger remove_item_btn">Remove</button>
                    </div>
                </div>
        </div>`)
        });

    });


    $(document).on('click','.remove_item_btn', function(e){
            e.preventDefault();
            let row_item = $(this).parent().parent();
            $(row_item).remove();

            });


    function populate(c1){
        var y = c1.split("_")
        var c1=document.getElementById(c1);
        var url = $("#personForm").attr("data-cities-url");  // get the url of the `load_courses` view
        var programmingId = c1.value; // get the selected programming ID from the HTML input
        $.ajax({                       // initialize an AJAX request
            url: url,                    // set the url of the request (= localhost:8000/load-courses/)
            data: {
            'category': programmingId       // add the programming id to the GET parameters
            },
            success: function (data) {   // `data` is the return of the `load_courses` view function
            $("#id_product_"+ y[1]).html(data);  // replace the contents of the course input with the data that came from the server
            }
        });

}


</script>
    {% endif %}
{% else %}
Login First
</div>
{% endif %}

{% endblock %}

spkapp/templates/order/postorderform.html
{% extends 'home/navi.html' %}
{% load static %}
{% block content %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Order Details</title>

     <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
     <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>

</head>
<body>
<br/> <br/>

{% if user.is_authenticated %}
    <div class="container-fluid well">
        {% if submitted %}
        <h3>Order was submitted successfully!</h3>
        {% else %}
        {% endif %}
    </div>

{% else %}
    Login First
{% endif %}
</body>
</html>
{% endblock %}